// Banco de ideas-demo de The MND130 Way.
// El generador NO combina ejes (eso daba combinaciones chotas): sortea UNA idea
// entera de este banco curado. Cada idea ya viene scopeada y lista para construir en vivo.
// Para rotar entre cohortes: marcá las usadas y, si querés, reordená o quitá las quemadas.

export type Idea = {
  nombre: string
  frase: string        // qué es, en una línea
  core: string         // las 3-5 features core del MVP
  estirar: string      // lo que queda para después (out-of-scope de la v1)
  llevaIA?: boolean    // true si el MVP tiene IA adentro (sirve para la Clase 3)
}

export const ideas: Idea[] = [
  { nombre: 'TurnoYa', frase: 'Reserva de turnos online para un profesional o local.',
    core: 'login, agenda con horarios disponibles, reservar/cancelar un turno.',
    estirar: 'recordatorios por mail, pagos, varias sucursales.' },
  { nombre: 'MiTablero', frase: 'Dashboard de métricas para una PyME, con carga manual.',
    core: 'login, cargar métricas, ver gráficos y la evolución en el tiempo.',
    estirar: 'integraciones automáticas, alertas, exportar reportes.' },
  { nombre: 'OnboardKit', frase: 'Checklist de onboarding para empleados nuevos.',
    core: 'roles admin/empleado, lista de tareas, marcar progreso.',
    estirar: 'firmas digitales, integración con RRHH, recordatorios.' },
  { nombre: 'AlquiGestión', frase: 'Gestión de propiedades en alquiler y sus pagos.',
    core: 'cargar propiedades, registrar pagos mensuales, ver morosos.',
    estirar: 'cobros reales, contratos, alertas de vencimiento.' },
  { nombre: 'ConnectPro', frase: 'Marketplace chico de servicios profesionales de nicho.',
    core: 'perfiles de profesionales, búsqueda por categoría, contacto.',
    estirar: 'pagos, reseñas, chat interno.' },
  { nombre: 'GastoClaro', frase: 'Gastos compartidos de un grupo (tipo viaje o roommates).',
    core: 'crear grupo, cargar gastos, calcular quién le debe a quién.',
    estirar: 'pagos reales, varias monedas, recordatorios.' },
  { nombre: 'StockSimple', frase: 'Control de inventario para un comercio chico.',
    core: 'cargar productos, ajustar stock, alerta de stock bajo.',
    estirar: 'códigos de barras, proveedores, órdenes de compra.' },
  { nombre: 'CitasMed', frase: 'Agenda de pacientes para un consultorio.',
    core: 'fichas de pacientes, agendar citas, ver la agenda del día.',
    estirar: 'historia clínica, recetas, recordatorios.' },
  { nombre: 'EventoYa', frase: 'Gestión de invitados a un evento, con RSVP.',
    core: 'crear evento, cargar invitados, confirmar asistencia.',
    estirar: 'venta de tickets, check-in con QR, mesas.' },
  { nombre: 'CursoFlow', frase: 'Mini-plataforma de cursos: clases y alumnos.',
    core: 'roles profe/alumno, lista de clases, marcar progreso.',
    estirar: 'video hosting, pagos, certificados.' },
  { nombre: 'PedidoFácil', frase: 'Toma de pedidos para un restorán o delivery chico.',
    core: 'menú, armar pedido, ver estados (recibido/listo/entregado).',
    estirar: 'pagos online, ruteo de delivery, cupones.' },
  { nombre: 'TareasEquipo', frase: 'Gestor de tareas tipo Trello reducido.',
    core: 'crear tareas, moverlas por estados, asignarlas a alguien.',
    estirar: 'tiempo real, comentarios, adjuntos.' },
  { nombre: 'SocioClub', frase: 'Gestión de socios de un club o gimnasio.',
    core: 'alta de socios, membresías con vencimiento, check-in manual.',
    estirar: 'cobro automático, control de acceso, clases.' },
  { nombre: 'ReclamoYa', frase: 'Mesa de reclamos/tickets para una empresa o municipio.',
    core: 'cargar reclamo, asignar prioridad y responsable, cambiar estado.',
    estirar: 'SLA automatizado, notificaciones, encuestas.' },
  { nombre: 'VetControl', frase: 'Fichas de mascotas para una veterinaria.',
    core: 'dueños, mascotas, registro de visitas.',
    estirar: 'recordatorios de vacunas, recetas, facturación.' },
  { nombre: 'FreelanceTrack', frase: 'Seguimiento de proyectos y horas de un freelancer.',
    core: 'proyectos, registrar horas, ver total facturable.',
    estirar: 'facturación legal, pagos, reportes por cliente.' },
  { nombre: 'CanchApp', frase: 'Reserva de canchas deportivas por horario.',
    core: 'grilla de horarios, ver disponibilidad, reservar.',
    estirar: 'pagos, torneos, ranking de jugadores.' },
  { nombre: 'MenuDigital', frase: 'Carta digital editable para un bar, con QR.',
    core: 'cargar platos por categoría, vista pública, panel de edición.',
    estirar: 'pedidos, pagos, control de stock.' },
  { nombre: 'PostulaT', frase: 'Bolsa de empleo chica para una PyME.',
    core: 'publicar búsquedas, recibir postulaciones, ver candidatos.',
    estirar: 'ranking de CVs con IA, matching, mensajería.' },
  { nombre: 'AhorroMeta', frase: 'Seguimiento de metas de ahorro personales.',
    core: 'crear metas, registrar aportes, ver progreso.',
    estirar: 'conexión bancaria, recordatorios, proyecciones.' },

  // --- Con IA adentro (sirven de demo para la Clase 3) ---
  { nombre: 'AsistenteFAQ', frase: 'Un bot que responde las preguntas frecuentes de un producto.', llevaIA: true,
    core: 'cargar las FAQs, pantalla de chat, respuestas basadas en esa info.',
    estirar: 'escalar a un humano, métricas de preguntas, varios idiomas.' },
  { nombre: 'ResumiReuniones', frase: 'Pegás las notas de una reunión y devuelve resumen + tareas.', llevaIA: true,
    core: 'pegar texto, generar resumen y lista de action items, guardarlos.',
    estirar: 'transcribir audio, asignar tareas, integraciones.' },
  { nombre: 'SoporteDocs', frase: 'Asistente que responde usando tus PDFs (manuales, políticas).', llevaIA: true,
    core: 'subir PDFs, hacer preguntas, respuestas que citan la fuente (RAG).',
    estirar: 'permisos por documento, varios idiomas, feedback.' },
  { nombre: 'CopyBot', frase: 'Generador de textos de marketing según producto y tono.', llevaIA: true,
    core: 'describir el producto y el tono, generar variantes, guardarlas.',
    estirar: 'publicar en redes, banco de marca, A/B testing.' },
  { nombre: 'TurnoBot', frase: 'Reservás un turno conversando con un agente, en vez de un formulario.', llevaIA: true,
    core: 'chat que entiende el pedido y usa herramientas para crear/cancelar turnos (tool use).',
    estirar: 'pagos, confirmación por mail, varios profesionales.' },
  { nombre: 'ClasificaTickets', frase: 'Lee un reclamo entrante y le asigna categoría y prioridad solo.', llevaIA: true,
    core: 'cargar un reclamo, que la IA lo clasifique, revisar y corregir.',
    estirar: 'asignación automática, integración con la mesa de ayuda.' },
]
